const $=s=>document.querySelector(s);
const DEFAULT_ORDER=`SiO2 TiO2 Al2O3 FeO Fe2O3 FeOT Fe2O3T MnO MgO CaO Na2O K2O P2O5 LOI Total La Ce Pr Nd Sm Eu Gd Tb Dy Ho Er Tm Yb Lu Y Li Be F Cl Sc V Cr Co Ni Cu Zn Ga Ge As Se Rb Sr Cs Ba Zr Hf Nb Ta Th U Pb W Sn Mo In Sb Ag Cd Te Tl Bi`.split(' ');
const ELEMENT_ALIASES={fe2o3t:'Fe2O3T',tfe2o3:'Fe2O3T',fe2o3total:'Fe2O3T','fe2o3 total':'Fe2O3T','total fe2o3':'Fe2O3T',totalfe2o3:'Fe2O3T',feot:'FeOT',tfeo:'FeOT',feototal:'FeOT','feo total':'FeOT','total feo':'FeOT',totalfeo:'FeOT',loi:'LOI','l.o.i.':'LOI'};
function canonical(name){let raw=String(name??'').trim(),lower=raw.toLowerCase();return ELEMENT_ALIASES[lower]||DEFAULT_ORDER.find(e=>e.toLowerCase()===lower)||raw}
let rows=[],cols=[],original=[],order=DEFAULT_ORDER.slice(),excludedElements=new Set(),sampleCol='',groupCol='',history=[];
let axis={x:{num:'',den:'',use:false,min:'',max:'',step:'',log:false,unitEnabled:false,unit:'%'},y:{num:'',den:'',use:false,min:'',max:'',step:'',log:false,unitEnabled:false,unit:'%'}};
let legendOverrides=new Map(),legendGroups=[],corelSvg='';
const demo=`Sample\tGroup\tLa\tZr\tY\tSiO2\tMgO\tTiO2\tNb\nA1-01\tA1\t18.2\t212\t24.1\t71.2\t0.35\t0.22\t12\nA1-02\tA1\t16.7\t198\t21.3\t70.8\t0.37\t0.25\t11\nA1-03\tA1\t20.1\t206\t26.8\t72.1\t0.35\t0.24\t13\nA2-01\tA2\t29.3\t301\t35.8\t67.3\t1.46\t0.41\t17\nA2-02\tA2\t31.1\t295\t33.1\t68.2\t1.18\t0.38\t16\nA2-03\tA2\t26.7\t322\t30.4\t66.9\t1.58\t0.45\t18\nA3-01\tA3\t42.1\t410\t48.6\t63.4\t2.67\t0.62\t22\nA3-02\tA3\t38.7\t395\t44.2\t64.1\t2.45\t0.59\t21\nA3-03\tA3\t45.3\t421\t52.4\t62.8\t2.85\t0.66\t23\nB1-01\tB1\t12.4\t180\t16.9\t59.1\t4.0\t0.77\t25\nB1-02\tB1\t11.8\t173\t17.8\t58.9\t4.06\t0.82\t26\nB1-03\tB1\t13.1\t188\t20.3\t60.2\t3.66\t0.74\t24\nB2-01\tB2\t8.4\t149\t14.2\t57.1\t4.62\t0.94\t31\nB2-02\tB2\t9.1\t158\t15.6\t56.8\t4.71\t0.91\t32\nB2-03\tB2\t8.9\t153\t13.9\t57.5\t4.5\t0.89\t30\nB3-01\tB3\t5.4\t140\t8.1\t54.3\t5.49\t1.06\t36\nB3-02\tB3\t6.1\t151\t9.4\t55.2\t5.21\t1.02\t35\nB3-03\tB3\t5.8\t146\t8.7\t54.9\t5.3\t1.08\t37\nC1-01\tC1\t23.2\t250\t28.1\t61.2\t3.35\t0.63\t20\nC1-02\tC1\t25.6\t263\t31.7\t62.1\t3.07\t0.60\t19\nC1-03\tC1\t24.1\t255\t29.9\t60.8\t3.47\t0.65\t21`;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nav(v){document.querySelectorAll('.view').forEach(e=>e.classList.toggle('active',e.id===v));document.querySelectorAll('.nav button').forEach(e=>e.classList.toggle('active',e.dataset.view===v));window.scrollTo(0,0);if(v==='plot')renderPlot()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>nav(b.dataset.view));$('#toPlot').onclick=()=>nav('plot');
function parseDelimited(text,sep){let out=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===sep&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);out.push(row);row=[];cell=''}else cell+=c}row.push(cell);out.push(row);return out}
function parsedMatrix(text){text=String(text||'').replace(/\u00a0/g,' ').trim();if(!text)throw Error('请粘贴内容');let matrix;if(/<table[\s>]/i.test(text)){let doc=new DOMParser().parseFromString(text,'text/html'),table=doc.querySelector('table');if(!table)throw Error('未找到表格');matrix=[...table.rows].map(tr=>[...tr.cells].map(td=>td.textContent.trim()))}else{let first=text.split(/\r?\n/)[0],sep=['\t',',',';'].sort((a,b)=>first.split(b).length-first.split(a).length)[0];matrix=parseDelimited(text,sep)}matrix=matrix.map(row=>row.map(v=>String(v??'').trim())).filter(row=>row.some(Boolean));let width=Math.max(0,...matrix.map(r=>r.length));let kept=Array.from({length:width},(_,i)=>i).filter(i=>matrix.some(r=>r[i]));matrix=matrix.map(row=>kept.map(i=>row[i]||''));if(matrix.length<2||matrix[0].length<2)throw Error('需要表头和至少一行数据');return matrix}
function normalizeMatrix(matrix){let headers=matrix[0],body=matrix.slice(1),norm=new Set([...DEFAULT_ORDER.map(x=>x.toLowerCase()),...Object.keys(ELEMENT_ALIASES)]),colHits=headers.slice(1).filter(v=>norm.has(v.toLowerCase())).length,rowHits=body.filter(r=>norm.has((r[0]||'').toLowerCase())).length,transposed=rowHits>colHits;if(transposed){matrix=[['SampleID',...body.map(r=>r[0])],...headers.slice(1).map((h,i)=>[h,...body.map(r=>r[i+1]||'')])];headers=matrix[0];body=matrix.slice(1)}headers=[headers[0].trim(),...headers.slice(1).map(canonical)];let seen=new Map(),warnings=[];headers=headers.map(h=>{let n=(seen.get(h)||0)+1;seen.set(h,n);if(n>1){warnings.push(`重复列 ${h} 已标为 ${h} (${n})`);return `${h} (${n})`}return h});return {headers,body,orientation:transposed?`自动转置：行匹配 ${rowHits} > 列匹配 ${colHits}`:`无需转置：列匹配 ${colHits}`,warnings}}
function parse(){let result;try{result=normalizeMatrix(parsedMatrix($('#source').value))}catch(e){$('#parseStatus').textContent=e.message;return}cols=result.headers;original=cols.slice();sampleCol=cols.find(c=>/^(sample|sample.?id|样品|样品编号|编号)$/i.test(c))||cols[0];groupCol=cols.find(c=>/^(group|分组|组别|类别)$/i.test(c))||'';rows=result.body.map((values,i)=>({id:i,selected:true,data:Object.fromEntries(cols.map((c,j)=>[c,values[j]??'']))}));let avail=cols.filter(c=>c!==sampleCol&&c!==groupCol);axis.x.num=avail.find(c=>/^SiO2$/i.test(c))||avail[0]||'';axis.y.num=avail.find(c=>/^MgO$/i.test(c))||avail.find(c=>c!==axis.x.num)||avail[0]||'';axis.x.den=axis.y.den='';axis.x.use=axis.y.use=false;$('#parseStatus').textContent=`解析成功 · ${result.orientation} · ${rows.length} 个样品${result.warnings.length?' · '+result.warnings.join('；'):''}`;renderAll()}
function optionMarkup(selected,blank=true){return (blank?'<option value="">留空</option>':'')+cols.map(c=>`<option value="${esc(c)}" ${c===selected?'selected':''}>${esc(c)}</option>`).join('')}
function effectiveOrder(){let present=cols.filter(c=>c!==sampleCol&&c!==groupCol),extra=present.filter(c=>!order.includes(c)).sort((a,b)=>a.localeCompare(b,undefined,{sensitivity:'base'}));return [...order,...extra].filter(c=>!excludedElements.has(c))}
function renderOrder(){
  const list=effectiveOrder(),present=new Set(cols),box=$('#order');
  $('#orderCount').textContent=`默认 ${DEFAULT_ORDER.length} 项 · 当前 ${list.length} 项`;
  box.innerHTML=list.map(c=>`<div role="listitem" tabindex="0" draggable="true" class="chip ${present.has(c)?'':'absent'}" data-col="${esc(c)}" aria-label="${esc(c)}，拖动或方向键调整顺序" title="拖动调整顺序；方向键微调"><span class="grip" aria-hidden="true">⋮⋮</span><span>${esc(c)}</span><button type="button" class="chip-remove" data-remove="${esc(c)}" aria-label="从排序中移除 ${esc(c)}" title="移除 ${esc(c)}">×</button></div>`).join('');
  box.querySelectorAll('.chip-remove').forEach(button=>button.onclick=e=>{e.stopPropagation();let col=button.dataset.remove;excludedElements.add(col);order=order.filter(c=>c!==col);$('#orderStatus').textContent=`已移除 ${col}；原始数据仍保留此列`;renderOrder();renderTables()});
  let dragged=null,touchSource=null;
  function move(source,target,after=false){let arr=effectiveOrder(),from=arr.indexOf(source),to=arr.indexOf(target);if(from<0||to<0||from===to)return;arr.splice(from,1);to=arr.indexOf(target)+(after?1:0);arr.splice(to,0,source);order=arr;$('#orderStatus').textContent=`${source} 已移到第 ${to+1} 位`;renderOrder();renderTables()}
  box.querySelectorAll('.chip').forEach(chip=>{
    chip.addEventListener('dragstart',e=>{if(e.target.closest('.chip-remove')){e.preventDefault();return}dragged=chip.dataset.col;chip.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',dragged)});
    chip.addEventListener('dragend',()=>{dragged=null;chip.classList.remove('dragging');box.querySelectorAll('.drag-target').forEach(x=>x.classList.remove('drag-target'))});
    chip.addEventListener('dragover',e=>{e.preventDefault();chip.classList.add('drag-target')});
    chip.addEventListener('dragleave',()=>chip.classList.remove('drag-target'));
    chip.addEventListener('drop',e=>{e.preventDefault();chip.classList.remove('drag-target');move(dragged||e.dataTransfer.getData('text/plain'),chip.dataset.col,e.clientX>chip.getBoundingClientRect().left+chip.offsetWidth/2)});
    chip.addEventListener('keydown',e=>{if(e.target!==chip||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();let arr=effectiveOrder(),i=arr.indexOf(chip.dataset.col),j=i+(e.key==='ArrowLeft'?-1:1);if(j<0||j>=arr.length)return;let target=arr[j];move(chip.dataset.col,target,e.key==='ArrowRight');[...box.querySelectorAll('.chip')].find(x=>x.dataset.col===chip.dataset.col)?.focus()});
    chip.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&!e.target.closest('.chip-remove'))touchSource=chip.dataset.col});
    chip.addEventListener('pointerup',e=>{if(e.pointerType!=='touch'||!touchSource)return;let target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.chip');if(target)move(touchSource,target.dataset.col);touchSource=null});
  });
}
function renderAll(){let sel=$('#sampleCol'),grp=$('#groupCol');sel.innerHTML=optionMarkup(sampleCol,false);grp.innerHTML=optionMarkup(groupCol);renderOrder();renderTables();renderAxis();renderPlot()}
$('#sampleCol').onchange=e=>{sampleCol=e.target.value;if(groupCol===sampleCol)groupCol='';renderAll()};$('#groupCol').onchange=e=>{groupCol=e.target.value;if(groupCol===sampleCol)groupCol='';renderAll()};$('#resetOrder').onclick=()=>{order=DEFAULT_ORDER.slice();excludedElements.clear();$('#orderStatus').textContent='已恢复默认顺序';renderOrder();renderTables()};$('#showPresent').onchange=renderTables;$('#parse').onclick=parse;$('#example').onclick=()=>{$('#source').value=demo;parse()};
$('#clearData').onclick=()=>{$('#source').value='';rows=[];cols=[];original=[];sampleCol='';groupCol='';axis.x.num=axis.y.num='';$('#parseStatus').textContent='数据已清空';renderAll()};
function addElement(){
  const input=$('#newElement'),name=canonical(input.value.trim());
  if(!name){$('#orderStatus').textContent='请先输入元素名称';return}
  if(name===sampleCol||name===groupCol){$('#orderStatus').textContent='该名称已用作样品或分组列';return}
  if(effectiveOrder().includes(name)&&cols.includes(name)){$('#orderStatus').textContent=`${name} 已在元素列表中`;return}
  order=effectiveOrder().filter(c=>c!==name);excludedElements.delete(name);order.push(name);
  if(!cols.includes(name)){cols.push(name);rows.forEach(r=>r.data[name]='')}
  input.value='';$('#orderStatus').textContent=`${name} 已添加到末尾；可在整理后的表格中填写数值`;
  renderOrder();renderTables();renderAxis();renderPlot();
}
$('#addElement').onclick=addElement;
$('#newElement').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addElement()}};
function group(r){return groupCol?(r.data[groupCol]||'未分组'):'全部样品'}
function plotGroup(r){return $('#groupPlot').checked?group(r):'全部样品'}
function renderTables(){let selected=rows.filter(r=>r.selected).length,all=rows.length>0&&selected===rows.length;$('#countSort').textContent=`${selected} / ${rows.length} 个样品参与投图`;$('#countPlot').textContent=`${selected} / ${rows.length}`;let ordered=effectiveOrder(),show=$('#showPresent').checked?ordered.filter(c=>cols.includes(c)):ordered;$('#columnStatus').textContent=`显示 ${show.length} / ${ordered.length} 个元素列`;$('#sortTable').innerHTML=`<thead><tr><th><input type="checkbox" class="master" aria-label="全选样品" ${all?'checked':''}></th><th>${esc(sampleCol||'样品')}</th><th>分组</th>${show.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr class="${r.selected?'':'excluded'}"><td><input type="checkbox" data-id="${r.id}" aria-label="选择 ${esc(r.data[sampleCol])}" ${r.selected?'checked':''}></td><td>${esc(r.data[sampleCol])}</td><td>${esc(group(r))}</td>${show.map(c=>`<td ${cols.includes(c)?`contenteditable="true" data-edit="${r.id}" data-col="${esc(c)}"`:'class="missing"'}>${esc(r.data[c]===''||r.data[c]==null?'na':r.data[c])}</td>`).join('')}</tr>`).join('')}</tbody>`;$('#plotTable').innerHTML=`<thead><tr><th><input class="master" aria-label="全选样品" type="checkbox" ${all?'checked':''}></th><th>样品</th><th>分组</th></tr></thead><tbody>${rows.map(r=>`<tr class="${r.selected?'':'excluded'}"><td><input type="checkbox" data-id="${r.id}" aria-label="选择 ${esc(r.data[sampleCol])}" ${r.selected?'checked':''}></td><td>${esc(r.data[sampleCol])}</td><td>${esc(group(r))}</td></tr>`).join('')}</tbody>`;document.querySelectorAll('.master').forEach(e=>e.onchange=ev=>{rows.forEach(r=>r.selected=ev.target.checked);renderTables();renderPlot()});document.querySelectorAll('[data-id]').forEach(e=>e.onchange=ev=>{rows[+ev.target.dataset.id].selected=ev.target.checked;renderTables();renderPlot()});document.querySelectorAll('[data-edit]').forEach(e=>e.onblur=()=>{let r=rows[+e.dataset.edit];r.data[e.dataset.col]=e.textContent.trim()==='na'?'':e.textContent.trim();renderPlot()});$('#quality').textContent=groupCol?`分组列：${groupCol} · 表格中的数据单元格可直接修改。`:'未发现分组列：所有样品默认归为一组。'}
$('#selectAll').onclick=()=>{rows.forEach(r=>r.selected=true);renderTables();renderPlot()};$('#selectNone').onclick=()=>{rows.forEach(r=>r.selected=false);renderTables();renderPlot()};$('#groupPlot').onchange=renderPlot;
function renderAxis(){
  let avail=cols.filter(c=>c!==sampleCol&&c!==groupCol);
  $('#axisControls').innerHTML=['x','y'].map(a=>`<div class="axis-card"><h3>${a.toUpperCase()} 轴 / ${a==='x'?'横轴':'纵轴'}</h3><div class="axis-row"><label>分子</label><select class="field" data-axis="${a}" data-key="num">${avail.map(c=>`<option value="${esc(c)}" ${axis[a].num===c?'selected':''}>${esc(c)}</option>`).join('')}</select></div><div class="axis-row"><label>分母</label><div class="denom"><input type="checkbox" aria-label="启用 ${a.toUpperCase()} 轴分母" data-axis="${a}" data-key="use" ${axis[a].use?'checked':''}><select class="field" aria-label="${a.toUpperCase()} 轴分母" data-axis="${a}" data-key="den" ${axis[a].use?'':'disabled'}><option value=""></option>${avail.map(c=>`<option value="${esc(c)}" ${axis[a].den===c?'selected':''}>${esc(c)}</option>`).join('')}</select></div></div><div class="axis-range">${['min','max','step'].map((k,i)=>`<label class="field">${['起始','结束','间隔'][i]}<input type="number" step="any" data-axis="${a}" data-key="${k}" value="${esc(axis[a][k])}" placeholder="自动"></label>`).join('')}</div><div class="axis-options"><label><input type="checkbox" data-axis="${a}" data-key="unitEnabled" ${axis[a].unitEnabled?'checked':''}> 单位</label><input type="text" aria-label="${a.toUpperCase()} 轴单位" data-axis="${a}" data-key="unit" value="${esc(axis[a].unit)}" placeholder="例如 ppm"><label class="axis-log"><input type="checkbox" data-axis="${a}" data-key="log" ${axis[a].log?'checked':''}> LOG10 数轴</label></div></div>`).join('');
  document.querySelectorAll('[data-axis]').forEach(el=>{let update=e=>{let a=e.target.dataset.axis,k=e.target.dataset.key;axis[a][k]=e.target.type==='checkbox'?e.target.checked:e.target.value;if(k==='use')renderAxis();renderPlot()};el.addEventListener('change',update);if(el.dataset.key==='unit')el.addEventListener('input',update)});
}
function axisName(a){let z=axis[a],name=z.num+(z.use&&z.den?'/'+z.den:'');return name+(z.unitEnabled&&z.unit.trim()?` (${z.unit.trim()})`:'')}
function value(r,a){let z=axis[a],n=Number(r.data[z.num]);if(!z.num||r.data[z.num]===''||!Number.isFinite(n))return NaN;if(z.use&&z.den){let d=Number(r.data[z.den]);if(r.data[z.den]===''||!Number.isFinite(d)||d===0)return NaN;n/=d}return z.log&&n<=0?NaN:n}
function family(g){return (g.match(/^[A-Za-z\u4e00-\u9fa5]+/)||[g])[0]}
function hslHex(h,s,l){s/=100;l/=100;let f=n=>{let k=(n+h/30)%12,a=s*Math.min(l,1-l);return Math.round(255*(l-a*Math.max(-1,Math.min(k-3,9-k,1)))).toString(16).padStart(2,'0')};return '#'+f(0)+f(8)+f(4)}
function defaultStyle(g,gs){let f=family(g),arr=gs.filter(x=>family(x)===f),idx=arr.indexOf(g),t=arr.length>1?idx/(arr.length-1):.5;let families=[...new Set(gs.map(family))],fi=families.indexOf(f),h=[2,204,38,277,175,24][fi%6],l=72-30*t;return {color:hslHex(h,80,l),shape:['circle','square','triangle','diamond'][fi%4],size:5.5,opacity:1}}
function style(g,gs){return {...defaultStyle(g,gs),...legendOverrides.get(g)}}
function blendWhite(hex,opacity){let a=Math.max(0,Math.min(1,opacity));return '#'+[1,3,5].map(i=>Math.round(parseInt(hex.slice(i,i+2),16)*a+255*(1-a)).toString(16).padStart(2,'0')).join('')}
function regularPoints(sides,x,y,r,inner=0){return Array.from({length:inner?sides*2:sides},(_,i)=>{let angle=-Math.PI/2+2*Math.PI*i/(inner?sides*2:sides),radius=inner&&i%2?inner:r;return `${(x+Math.cos(angle)*radius).toFixed(2)},${(y+Math.sin(angle)*radius).toFixed(2)}`}).join(' ')}
function markerMarkup(st,x,y,title='',flat=false){
  const size=st.size,color=flat?blendWhite(st.color,st.opacity):st.color;
  const stroke=flat?blendWhite('#26313a',st.opacity):'#26313a';
  const attrs=`fill="${color}" stroke="${stroke}" stroke-width="0.8"${!flat&&st.opacity<1?` opacity="${st.opacity}"`:''}`;
  const hint=title?`<title>${esc(title)}</title>`:'';
  if(st.shape==='circle')return hint?`<circle cx="${x}" cy="${y}" r="${size}" ${attrs}>${hint}</circle>`:`<circle cx="${x}" cy="${y}" r="${size}" ${attrs}/>`;
  if(st.shape==='square')return hint?`<rect x="${x-size}" y="${y-size}" width="${size*2}" height="${size*2}" ${attrs}>${hint}</rect>`:`<rect x="${x-size}" y="${y-size}" width="${size*2}" height="${size*2}" ${attrs}/>`;
  let points;
  if(st.shape==='triangle')points=regularPoints(3,x,y,size*1.35);
  else if(st.shape==='pentagon')points=regularPoints(5,x,y,size*1.3);
  else if(st.shape==='hexagon')points=regularPoints(6,x,y,size*1.3);
  else if(st.shape==='star')points=regularPoints(5,x,y,size*1.4,size*.58);
  else if(st.shape==='cross'){let a=size*.48,r=size*1.32;points=[[-a,-r],[a,-r],[a,-a],[r,-a],[r,a],[a,a],[a,r],[-a,r],[-a,a],[-r,a],[-r,-a],[-a,-a]].map(([dx,dy])=>`${(x+dx).toFixed(2)},${(y+dy).toFixed(2)}`).join(' ')}
  else points=regularPoints(4,x,y,size*1.35);
  return hint?`<polygon points="${points}" ${attrs}>${hint}</polygon>`:`<polygon points="${points}" ${attrs}/>`;
}
function tick(v){return Math.abs(v)>=1000?v.toExponential(1):Number(v.toPrecision(3)).toString()}function renderPlot(){if(!rows.length){corelSvg='';$('#legend').innerHTML='';$('#chart').innerHTML='<div class="notice" style="padding:40px">请先在“数据导入”中粘贴数据。</div>';$('#stats').innerHTML='';return}let data=rows.filter(r=>r.selected).map(r=>({r,x:value(r,'x'),y:value(r,'y'),g:plotGroup(r)})),valid=data.filter(d=>Number.isFinite(d.x)&&Number.isFinite(d.y));let bad=data.length-valid.length,gs=[...new Set(valid.map(d=>d.g))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));$('#plotNotice').textContent=`已选择 ${data.length} 个样品 · 有效投图 ${valid.length} 个 · 缺失、零分母或对数轴非正值排除 ${bad} 个。`;$('#chartTitle').textContent=`${axisName('x')} vs ${axisName('y')}`;const W=460,H=360,L=74,R=26,T=22,B=68,pw=W-L-R,ph=H-T-B;let vals=a=>valid.map(d=>a==='x'?d.x:d.y),limits={};for(let a of ['x','y']){let z=axis[a],v=vals(a),mn=Math.min(...v),mx=Math.max(...v);if(!v.length){mn=z.log?.1:0;mx=z.log?10:1}let low=z.min!==''?+z.min:(z.log?10**Math.floor(Math.log10(mn)):mn-(mx-mn||1)*.08),high=z.max!==''?+z.max:(z.log?10**Math.ceil(Math.log10(mx)):mx+(mx-mn||1)*.08);if(z.log&&low<=0)low=mn>0?mn/2:.1;if(!(high>low))high=low+(z.log?low*10:1);limits[a]={low,high,lo:z.log?Math.log10(low):low,hi:z.log?Math.log10(high):high}}let pos=(v,a)=>{let z=axis[a],b=limits[a],u=z.log?Math.log10(v):v;return a==='x'?L+(u-b.lo)/(b.hi-b.lo)*pw:T+ph-(u-b.lo)/(b.hi-b.lo)*ph};let ticks=a=>{let z=axis[a],b=limits[a],s=Number(z.step),ar=[];if(z.log){let begin=Math.ceil(Math.log10(b.low)),end=Math.floor(Math.log10(b.high));for(let k=begin;k<=end&&ar.length<30;k++)ar.push(10**k)}else if(s>0){for(let t=Math.ceil(b.low/s)*s;t<=b.high&&ar.length<35;t+=s)ar.push(t)}else for(let i=0;i<=5;i++)ar.push(b.low+(b.high-b.low)*i/5);return ar};let grid=ticks('x').map(v=>`<line x1="${pos(v,'x')}" y1="${T}" x2="${pos(v,'x')}" y2="${T+ph}" stroke="#c9cfd3"/><text x="${pos(v,'x')}" y="${T+ph+25}" text-anchor="middle" fill="#222b33" font-size="13">${tick(v)}</text>`).join('')+ticks('y').map(v=>`<line x1="${L}" y1="${pos(v,'y')}" x2="${L+pw}" y2="${pos(v,'y')}" stroke="#c9cfd3"/><text x="${L-13}" y="${pos(v,'y')+4}" text-anchor="end" fill="#222b33" font-size="13">${tick(v)}</text>`).join('');let marks=valid.filter(d=>d.x>=limits.x.low&&d.x<=limits.x.high&&d.y>=limits.y.low&&d.y<=limits.y.high).map(d=>{
  return {d,x:pos(d.x,'x'),y:pos(d.y,'y'),st:style(d.g,gs)};
});
let liveMarks=marks.map(({d,x,y,st})=>markerMarkup(st,x,y,`${d.r.data[sampleCol]} · ${d.g} · X ${tick(d.x)} · Y ${tick(d.y)}`)).join('');
let editableMarks=marks.map(({x,y,st})=>markerMarkup(st,x,y,'',true)).join('');
const frame=`<rect x="${L}" y="${T}" width="${pw}" height="${ph}" fill="#ffffff" stroke="#1e252b" stroke-width="1.5"/>`;
const axes=`<text x="${L+pw/2}" y="${H-22}" text-anchor="middle" font-family="Arial, sans-serif" fill="#111820" font-size="17">${esc(axisName('x'))}${axis.x.log?' (LOG10)':''}</text><text x="${L}" y="22" font-family="Arial, sans-serif" fill="#111820" font-size="17">${esc(axisName('y'))}${axis.y.log?' (LOG10)':''}</text>`;
let svg=`<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(axisName('x'))} 与 ${esc(axisName('y'))} 散点图"><rect width="${W}" height="${H}" fill="#ffffff"/>${frame}${grid}${liveMarks}${axes}</svg>`;
corelSvg=`<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">${frame}${grid}${editableMarks}${axes}</svg>`;
$('#chart').innerHTML=svg;
legendGroups=gs;
$('#legend').innerHTML=gs.map(g=>{let st=style(g,gs),icon=markerMarkup({...st,size:Math.min(st.size,8)},12,12);return `<button type="button" class="legend-item" data-group="${esc(g)}" aria-label="编辑 ${esc(g)} 图例"><svg viewBox="0 0 24 24" aria-hidden="true">${icon}</svg><span>${esc(g)}</span></button>`}).join('');
$('#legend').querySelectorAll('.legend-item').forEach(button=>button.onclick=()=>openLegend(button.dataset.group));
renderStats(valid,gs);
}
let editingGroup='';
const SHAPES=[['circle','圆形'],['square','方形'],['diamond','菱形'],['triangle','三角形'],['pentagon','五边形'],['hexagon','六边形'],['star','五角星'],['cross','十字形']];
function legendInput(){
  let sizeField=$('#legendSizeNumber').value,transField=$('#legendTransparencyNumber').value;
  let size=Math.max(2,Math.min(24,Number(sizeField===''?$('#legendSize').value:sizeField)));
  let transparency=Math.max(0,Math.min(100,Number(transField===''?$('#legendTransparency').value:transField)));
  return {shape:$('#legendShape').value,color:$('#legendColor').value,size,opacity:1-transparency/100};
}
function renderShapePicker(){
  let selected=$('#legendShape').value,color=$('#legendColor').value;
  let current=SHAPES.find(([key])=>key===selected)||SHAPES[0];
  $('#legendShapeLabel').innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true">${markerMarkup({shape:current[0],color,size:5.5,opacity:1},12,12)}</svg><span>${current[1]}</span><span aria-hidden="true">⌄</span>`;
  $('#legendShapeOptions').innerHTML=SHAPES.map(([key,name])=>`<button type="button" role="option" aria-selected="${key===selected}" data-shape="${key}"><svg viewBox="0 0 24 24" aria-hidden="true">${markerMarkup({shape:key,color,size:5.5,opacity:1},12,12)}</svg><span>${name}</span></button>`).join('');
  $('#legendShapeOptions').querySelectorAll('button').forEach(button=>button.onclick=()=>{$('#legendShape').value=button.dataset.shape;$('#legendShapePicker').open=false;renderShapePicker();updateLegendPreview()});
}
function showLegendStyle(st){
  $('#legendShape').value=st.shape;$('#legendColor').value=st.color;
  $('#legendSize').value=st.size;$('#legendSizeNumber').value=st.size;
  let transparency=Number(((1-st.opacity)*100).toFixed(2));
  $('#legendTransparency').value=transparency;$('#legendTransparencyNumber').value=transparency;
  renderShapePicker();updateLegendPreview();
}
function updateLegendPreview(){let st=legendInput();$('#legendPreview').innerHTML=markerMarkup({...st,size:Math.min(st.size*1.4,16)},28,28)}
function openLegend(group){editingGroup=group;$('#legendDialogTitle').textContent=`${group} · 图例设置`;$('#legendGroup').textContent=group;showLegendStyle(style(group,legendGroups));let dialog=$('#legendDialog');if(dialog.showModal)dialog.showModal();else dialog.setAttribute('open','')}
function closeLegend(){let dialog=$('#legendDialog');if(dialog.close)dialog.close();else dialog.removeAttribute('open')}
$('#legendColor').oninput=()=>{renderShapePicker();updateLegendPreview()};
$('#legendSize').oninput=()=>{$('#legendSizeNumber').value=$('#legendSize').value;updateLegendPreview()};
$('#legendSizeNumber').oninput=()=>{if($('#legendSizeNumber').value!==''){$('#legendSize').value=$('#legendSizeNumber').value;updateLegendPreview()}};
$('#legendSizeNumber').onchange=()=>{$('#legendSizeNumber').value=legendInput().size;updateLegendPreview()};
$('#legendTransparency').oninput=()=>{$('#legendTransparencyNumber').value=$('#legendTransparency').value;updateLegendPreview()};
$('#legendTransparencyNumber').oninput=()=>{if($('#legendTransparencyNumber').value!==''){$('#legendTransparency').value=$('#legendTransparencyNumber').value;updateLegendPreview()}};
$('#legendTransparencyNumber').onchange=()=>{$('#legendTransparencyNumber').value=Number(((1-legendInput().opacity)*100).toFixed(2));updateLegendPreview()};
$('#legendApply').onclick=()=>{if(!editingGroup)return;legendOverrides.set(editingGroup,legendInput());closeLegend();renderPlot()};
$('#legendReset').onclick=()=>{if(editingGroup)showLegendStyle(defaultStyle(editingGroup,legendGroups))};
$('#legendCancel').onclick=$('#legendClose').onclick=closeLegend;
function rank(v){return v.map(x=>({x})).map((o,i)=>({...o,i})).sort((a,b)=>a.x-b.x).reduce((out,o,j,arr)=>{let k=j;while(k+1<arr.length&&arr[k+1].x===o.x)k++;for(let n=j;n<=k;n++)out[arr[n].i]=(j+k)/2+1;return out},[])}function pearson(x,y){let n=x.length,sx=x.reduce((a,b)=>a+b,0)/n,sy=y.reduce((a,b)=>a+b,0)/n,a=0,b=0,c=0;for(let i=0;i<n;i++){let dx=x[i]-sx,dy=y[i]-sy;a+=dx*dy;b+=dx*dx;c+=dy*dy}return b*c?Math.max(-1,Math.min(1,a/Math.sqrt(b*c))):NaN}function logGamma(z){let p=[.99999999999980993,676.5203681218851,-1259.1392167224028,771.32342877765313,-176.6150291621406,12.507343278686905,-.13857109526572012,9.984369578019572e-6,1.5056327351493116e-7];if(z<.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-logGamma(1-z);z--;let x=p[0];for(let i=1;i<p.length;i++)x+=p[i]/(z+i);let t=z+7.5;return .5*Math.log(2*Math.PI)+(z+.5)*Math.log(t)-t+Math.log(x)}function betacf(a,b,x){let qab=a+b,qap=a+1,qam=a-1,c=1,d=1-qab*x/qap;if(Math.abs(d)<1e-30)d=1e-30;d=1/d;let h=d;for(let m=1;m<=150;m++){let m2=2*m,aa=m*(b-m)*x/((qam+m2)*(a+m2));d=1+aa*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;h*=d*c;aa=-(a+m)*(qab+m)*x/((a+m2)*(qap+m2));d=1+aa*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;let del=d*c;h*=del;if(Math.abs(del-1)<3e-12)break}return h}function ibeta(x,a,b){if(x<=0)return 0;if(x>=1)return 1;let bt=Math.exp(logGamma(a+b)-logGamma(a)-logGamma(b)+a*Math.log(x)+b*Math.log(1-x));return x<(a+1)/(a+b+2)?bt*betacf(a,b,x)/a:1-bt*betacf(b,a,1-x)/b}function pvalue(r,n){if(n<3||!Number.isFinite(r))return NaN;if(Math.abs(r)>=1)return 0;return ibeta(1-r*r,(n-2)/2,.5)}function renderStats(data,gs){let m=$('#method').value;$('#stats').innerHTML=gs.length?gs.map(g=>{let d=data.filter(x=>x.g===g),x=d.map(z=>z.x),y=d.map(z=>z.y),r=m==='spearman'?pearson(rank(x),rank(y)):pearson(x,y),p=pvalue(r,d.length),s=style(g,gs);return `<div class="stat"><strong><span class="swatch" style="background:${s.color}"></span>${esc(g)}</strong><br>${m==='pearson'?'Pearson r':'Spearman ρ'}：${Number.isFinite(r)?r.toFixed(3):'—'}<br>p 值：${Number.isFinite(p)?p<.001?'&lt;0.001':p.toFixed(3):'—'}<br>有效 n：${d.length}${d.length<3?'<br>样本不足，无法计算 p 值':''}</div>`}).join(''):'<div class="notice">暂无可计算的数据。</div>'}$('#method').onchange=renderPlot;
function download(name,content,type){let url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function sortedSnapshot(selectedOnly=true){let keys=[sampleCol,groupCol||'分组',...effectiveOrder()];let result=(selectedOnly?rows.filter(r=>r.selected):rows).map(r=>keys.map(k=>k==='分组'&&!groupCol?group(r):r.data[k]===''||r.data[k]==null?'na':r.data[k]));return {keys,result}}
$('#svgExport').onclick=()=>{if(corelSvg)download('geochemistry-xy.svg',corelSvg,'image/svg+xml;charset=utf-8')};
$('#pngExport').onclick=()=>{let svg=$('#chart svg');if(!svg)return;let blob=new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),im=new Image;im.onload=()=>{let c=document.createElement('canvas');c.width=920;c.height=720;let ctx=c.getContext('2d');ctx.drawImage(im,0,0,c.width,c.height);c.toBlob(b=>{if(b){let u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='geochemistry-xy.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}URL.revokeObjectURL(url)},'image/png')};im.src=url};
function historyRows(){return history.flatMap((b,i)=>b.result.map(row=>{let record={'批次':i+1,'时间':b.time};b.keys.forEach((k,j)=>record[k]=row[j]);return record}))}
function renderHistory(){let count=history.reduce((n,b)=>n+b.result.length,0);$('#historyCount').textContent=history.length?`${history.length} 批 · ${count} 个样品`:'尚无批次';let union=['批次','时间',...new Set(history.flatMap(b=>b.keys))],entries=historyRows();$('#historyTable').innerHTML=entries.length?`<thead><tr>${union.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${entries.slice(0,50).map(r=>`<tr>${union.map(c=>`<td>${esc(r[c]??'na')}</td>`).join('')}</tr>`).join('')}</tbody>`:'<tbody><tr><td>暂无汇总记录</td></tr></tbody>';$('#historyTable').dataset.columns=JSON.stringify(union);$('#historyTsv').value=entries.length?[union,...entries.map(r=>union.map(c=>r[c]??'na'))].map(row=>row.join('\t')).join('\n'):''}
$('#addBatch').onclick=()=>{let snapshot=sortedSnapshot();if(!snapshot.result.length){$('#historyStatus').textContent='当前没有已勾选数据';return}history.push({...snapshot,time:new Date().toLocaleTimeString('zh-CN',{hour12:false})});$('#historyStatus').textContent=`已添加第 ${history.length} 批`;renderHistory()};
$('#copyTsv').onclick=async()=>{let t=$('#historyTsv');if(!t.value){$('#historyStatus').textContent='请先汇总结果';return}try{await navigator.clipboard.writeText(t.value)}catch{t.select();document.execCommand('copy')}$('#historyStatus').textContent='数据已复制'};
$('#clearHistory').onclick=()=>{history=[];$('#historyTsv').value='';$('#historyStatus').textContent='记录已清空';renderHistory()};
$('#source').value=demo;parse();renderHistory();
